name: Run HTML File

on:
  push:
    branches:
      - main

jobs:
  run-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start web server
      run: |
        python3 -m http.server 8000
      working-directory: ./Stack_fusion

    - name: Print URL
      run: |
        echo "Access your HTML file at: http://localhost:8000/index.html"
